apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mzokgdkbp-go 
  janus-idp.io/tekton: mzokgdkbp-go
  backstage.io/kubernetes-id: mzokgdkbp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mzokgdkbp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  